### PR TITLE
Improve syntax in order to avoid breaking most used eslint rules

### PR DESCRIPTION
**Pull request by jonathanpalma**
During the time that I have been using this library I have realized that sometimes refactoring the code generated by using the snippets that breaks my eslint rules decreases my productivity. That's why I spend some time working in the following tasks.

- added semicolons where needed
- fixed some indentantion issues inside blocks
- removed reactAnonymousFunctionalComponent due to SyntaxError. For a better reference https://stackoverflow.com/a/36261387
- fixed setupReactComponentTestWithRedux misspelling ')'
- updated documentation with most of these changes

### CODE REVIEW

**Comment by dsznajder** [comment]
@jonathanpalma I do not use the semicolons, so I won't add this one to the library. If you facing issues with this one, you can try some with those inside. Rest seems to be fine, but i need to test it on my own yet :)

**Comment by jonathanpalma** [comment]
@dsznajder There isn't any issue with this lib, as I mentioned in my comment I just feel that refactor the generated code (add semicolons, indentation, etc) every time I use it decreases my productivity.

At least can you please have a look at 
- removed `reactAnonymousFunctionalComponent` due to SyntaxError. For a better reference https://stackoverflow.com/a/36261387
- fixed `setupReactComponentTestWithRedux` misspelling ')'

I can send a different PR in order to fix those in case you find an issue.

**Comment by dsznajder** [comment]
As I mentioned, rest is fine :) If you remove and rebase the conflicts I can merge it and release

**Comment by dsznajder** [comment]
@jonathanpalma The fixes have been applied for now so I'm closing this PR as it's unrelated. I'm researching the topic of adding some settings for double/single quotes and semicolons but I will not hard code them inside snippets

**Pull request closed without merging**
