### PR TITLE
Added TypeScript snippets

### PR DESCRIPTION
**Pull request by vadymbiliuk**
I've added snippets for typescript language, with simple basic typing by interfaces

### CODE REVIEW

**Comment by dsznajder** [comment]
@vadymbiliuk Thank you!, I'm thinking if it's not better to alias this one with `ts` not only `t` as it can be mislead in future

**Comment by vadymbiliuk** [comment]
@dsznajder i can add 'ts' alias for all ts snippets if u wish ^^. 
Also should i update a readme file?

**Comment by dsznajder** [comment]
@vadymbiliuk Yes, I would like a ts alias :) Also, I'm thinking about splitting ts snippets from normal js to make them exclusive in `.ts` `.tsx` files, but I need investigate this one :)

**Comment by vadymbiliuk** [comment]
> @vadymbiliuk Yes, I would like a ts alias :) Also, I'm thinking about splitting ts snippets from `.js` to make them exclusive in `.ts` `.tsx` files, but I need investigate this one :)
I've been thinking about the same! xD
I need investigate that ither. Also i would like to help if i can :3

**Comment by dsznajder** [comment]
@vadymbiliuk I will research topic and get back to you.

**Comment by dsznajder** [comment]
@vadymbiliuk I'm pretty sure that we could done something like this:
https://code.visualstudio.com/api/language-extensions/snippet-guide
I do not know yet if we can pass array of languages to this one. -> need to check on your branch

**Comment by dsznajder** [comment]
@vadymbiliuk Ok, it seems to be working if you add next ones in `package.json`:
```
"snippets": [
      {
        "language": "javascript",
        "path": "./snippets/snippets.json"
      },
      {
        "language": "javascriptreact",
        "path": "./snippets/snippets.json"
      },
      {
        "language": "typescript",
        "path": "./snippets/snippets.json"
      },
      {
        "language": "typescript",
        "path": "./snippets/snippets-ts.json"
      },
      {
        "language": "typescriptreact",
        "path": "./snippets/snippets.json"
      },
      {
        "language": "typescriptreact",
        "path": "./snippets/snippets-ts.json"
      }
    ]
```

But, I'm figuring out how to add this to `extension/index.ts` :)

**Comment by vadymbiliuk** [comment]
@dsznajder yeah i've found that already
I think i can implement that. I'll do that when i will be free

**Comment by dsznajder** [comment]
@vadymbiliuk Ok, I will handle the extension search on my own later :)

**Comment by vadymbiliuk** [comment]
@dsznajder i did that. But i'm not really sure about how much my solution is beautiful. I was trying to split same parts from javascript.json and typescript.json into base.json but i haven't found solution for that :/
How is it looks for you now?

**Comment by dsznajder** [comment]
@vadymbiliuk Not quite as I planned :). You should add only your snippets to `typescript.json` and include both files for `typescript` and `typescriptreact`. Rest should be untouched.

**Comment by vadymbiliuk** [comment]
@dsznajder pardon mate. My bad :C
Now it's should looks just like you imagined it

**Comment by vadymbiliuk** [comment]
@dsznajder idk about stuff like snippets with PropTypes. Those should be still available in ts/tsx, but it's useless for typescript xd

**Comment by dsznajder** [comment]
@vadymbiliuk Ok thank you for this :) Anyway, I can't release it cos extension which search for snippets won't find those as I tested. I will try to figure it out soon :)

**Pull request merged**
